// Code generated from GitHub Linguist language colors. DO NOT EDIT.
// Source: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml
// License: MIT (https://github.com/github/linguist/blob/master/LICENSE)

package render

import "github.com/charmbracelet/lipgloss"

// githubLangColors maps language names to the colors used by GitHub Linguist.
var githubLangColors = map[string]lipgloss.Color{
	"1C Enterprise":                   lipgloss.Color("#814CCC"),
	"2-Dimensional Array":             lipgloss.Color("#38761D"),
	"4D":                              lipgloss.Color("#004289"),
	"ABAP":                            lipgloss.Color("#E8274B"),
	"ABAP CDS":                        lipgloss.Color("#555e25"),
	"AGS Script":                      lipgloss.Color("#B9D9FF"),
	"AIDL":                            lipgloss.Color("#34EB6B"),
	"AL":                              lipgloss.Color("#3AA2B5"),
	"ALGOL":                           lipgloss.Color("#D1E0DB"),
	"AMPL":                            lipgloss.Color("#E6EFBB"),
	"ANTLR":                           lipgloss.Color("#9DC3FF"),
	"API Blueprint":                   lipgloss.Color("#2ACCA8"),
	"APL":                             lipgloss.Color("#5A8164"),
	"ASP.NET":                         lipgloss.Color("#9400ff"),
	"ATS":                             lipgloss.Color("#1ac620"),
	"ActionScript":                    lipgloss.Color("#882B0F"),
	"Ada":                             lipgloss.Color("#02f88c"),
	"Adblock Filter List":             lipgloss.Color("#800000"),
	"Adobe Font Metrics":              lipgloss.Color("#fa0f00"),
	"Agda":                            lipgloss.Color("#315665"),
	"Aiken":                           lipgloss.Color("#640ff8"),
	"Alloy":                           lipgloss.Color("#64C800"),
	"Alpine Abuild":                   lipgloss.Color("#0D597F"),
	"Altium Designer":                 lipgloss.Color("#A89663"),
	"AngelScript":                     lipgloss.Color("#C7D7DC"),
	"Answer Set Programming":          lipgloss.Color("#A9CC29"),
	"Ant Build System":                lipgloss.Color("#A9157E"),
	"Antlers":                         lipgloss.Color("#ff269e"),
	"ApacheConf":                      lipgloss.Color("#d12127"),
	"Apex":                            lipgloss.Color("#1797c0"),
	"Apollo Guidance Computer":        lipgloss.Color("#0B3D91"),
	"AppleScript":                     lipgloss.Color("#101F1F"),
	"Arc":                             lipgloss.Color("#aa2afe"),
	"AsciiDoc":                        lipgloss.Color("#73a0c5"),
	"AspectJ":                         lipgloss.Color("#a957b0"),
	"Assembly":                        lipgloss.Color("#6E4C13"),
	"Astro":                           lipgloss.Color("#ff5a03"),
	"Asymptote":                       lipgloss.Color("#ff0000"),
	"Augeas":                          lipgloss.Color("#9CC134"),
	"AutoHotkey":                      lipgloss.Color("#6594b9"),
	"AutoIt":                          lipgloss.Color("#1C3552"),
	"Avro IDL":                        lipgloss.Color("#0040FF"),
	"Awk":                             lipgloss.Color("#c30e9b"),
	"B (Formal Method)":               lipgloss.Color("#8aa8c5"),
	"B4X":                             lipgloss.Color("#00e4ff"),
	"BAML":                            lipgloss.Color("#a855f7"),
	"BASIC":                           lipgloss.Color("#ff0000"),
	"BQN":                             lipgloss.Color("#2b7067"),
	"Ballerina":                       lipgloss.Color("#FF5000"),
	"Batchfile":                       lipgloss.Color("#C1F12E"),
	"Beef":                            lipgloss.Color("#a52f4e"),
	"Berry":                           lipgloss.Color("#15A13C"),
	"BibTeX":                          lipgloss.Color("#778899"),
	"Bicep":                           lipgloss.Color("#519aba"),
	"Bikeshed":                        lipgloss.Color("#5562ac"),
	"Bison":                           lipgloss.Color("#6A463F"),
	"BitBake":                         lipgloss.Color("#00bce4"),
	"Blade":                           lipgloss.Color("#f7523f"),
	"BlitzBasic":                      lipgloss.Color("#00FFAE"),
	"BlitzMax":                        lipgloss.Color("#cd6400"),
	"Blueprint":                       lipgloss.Color("#3584E4"),
	"Bluespec":                        lipgloss.Color("#12223c"),
	"Bluespec BH":                     lipgloss.Color("#12223c"),
	"Boo":                             lipgloss.Color("#d4bec1"),
	"Boogie":                          lipgloss.Color("#c80fa0"),
	"Brainfuck":                       lipgloss.Color("#2F2530"),
	"BrighterScript":                  lipgloss.Color("#66AABB"),
	"Brightscript":                    lipgloss.Color("#662D91"),
	"Browserslist":                    lipgloss.Color("#ffd539"),
	"Bru":                             lipgloss.Color("#F4AA41"),
	"BuildStream":                     lipgloss.Color("#006bff"),
	"C":                               lipgloss.Color("#555555"),
	"C#":                              lipgloss.Color("#7355dd"),
	"C++":                             lipgloss.Color("#f34b7d"),
	"C3":                              lipgloss.Color("#2563eb"),
	"CAP CDS":                         lipgloss.Color("#0092d1"),
	"CLIPS":                           lipgloss.Color("#00A300"),
	"CMake":                           lipgloss.Color("#DA3434"),
	"COLLADA":                         lipgloss.Color("#F1A42B"),
	"CQL":                             lipgloss.Color("#006091"),
	"CSON":                            lipgloss.Color("#244776"),
	"CSS":                             lipgloss.Color("#663399"),
	"CSV":                             lipgloss.Color("#237346"),
	"CUE":                             lipgloss.Color("#5886E1"),
	"CWeb":                            lipgloss.Color("#00007a"),
	"Cabal Config":                    lipgloss.Color("#483465"),
	"Caddyfile":                       lipgloss.Color("#22b638"),
	"Cadence":                         lipgloss.Color("#00ef8b"),
	"Cairo":                           lipgloss.Color("#ff4a48"),
	"Cairo Zero":                      lipgloss.Color("#ff4a48"),
	"CameLIGO":                        lipgloss.Color("#3be133"),
	"Cangjie":                         lipgloss.Color("#00868B"),
	"Cap'n Proto":                     lipgloss.Color("#c42727"),
	"Carbon":                          lipgloss.Color("#222222"),
	"Ceylon":                          lipgloss.Color("#dfa535"),
	"Chapel":                          lipgloss.Color("#8dc63f"),
	"ChucK":                           lipgloss.Color("#3f8000"),
	"Circom":                          lipgloss.Color("#707575"),
	"Cirru":                           lipgloss.Color("#ccccff"),
	"Clarion":                         lipgloss.Color("#db901e"),
	"Clarity":                         lipgloss.Color("#5546ff"),
	"Classic ASP":                     lipgloss.Color("#6a40fd"),
	"Clean":                           lipgloss.Color("#3F85AF"),
	"Click":                           lipgloss.Color("#E4E6F3"),
	"Clojure":                         lipgloss.Color("#db5855"),
	"Closure Templates":               lipgloss.Color("#0d948f"),
	"Cloud Firestore Security Rules":  lipgloss.Color("#FFA000"),
	"Clue":                            lipgloss.Color("#0009b5"),
	"CodeQL":                          lipgloss.Color("#140f46"),
	"CoffeeScript":                    lipgloss.Color("#244776"),
	"ColdFusion":                      lipgloss.Color("#ed2cd6"),
	"ColdFusion CFC":                  lipgloss.Color("#ed2cd6"),
	"Common Lisp":                     lipgloss.Color("#3fb68b"),
	"Common Workflow Language":        lipgloss.Color("#B5314C"),
	"Component Pascal":                lipgloss.Color("#B0CE4E"),
	"Cooklang":                        lipgloss.Color("#E15A29"),
	"Crystal":                         lipgloss.Color("#000100"),
	"Csound":                          lipgloss.Color("#1a1a1a"),
	"Csound Document":                 lipgloss.Color("#1a1a1a"),
	"Csound Score":                    lipgloss.Color("#1a1a1a"),
	"Cuda":                            lipgloss.Color("#3A4E3A"),
	"Curry":                           lipgloss.Color("#531242"),
	"Cylc":                            lipgloss.Color("#00b3fd"),
	"Cypher":                          lipgloss.Color("#34c0eb"),
	"Cython":                          lipgloss.Color("#fedf5b"),
	"D":                               lipgloss.Color("#ba595e"),
	"D2":                              lipgloss.Color("#526ee8"),
	"DM":                              lipgloss.Color("#447265"),
	"Dafny":                           lipgloss.Color("#FFEC25"),
	"Darcs Patch":                     lipgloss.Color("#8eff23"),
	"Dart":                            lipgloss.Color("#00B4AB"),
	"Daslang":                         lipgloss.Color("#d3d3d3"),
	"DataWeave":                       lipgloss.Color("#003a52"),
	"Debian Package Control File":     lipgloss.Color("#D70751"),
	"DenizenScript":                   lipgloss.Color("#FBEE96"),
	"Dhall":                           lipgloss.Color("#dfafff"),
	"DirectX 3D File":                 lipgloss.Color("#aace60"),
	"Dockerfile":                      lipgloss.Color("#384d54"),
	"Dogescript":                      lipgloss.Color("#cca760"),
	"Dotenv":                          lipgloss.Color("#e5d559"),
	"Dune":                            lipgloss.Color("#89421e"),
	"Dylan":                           lipgloss.Color("#6c616e"),
	"E":                               lipgloss.Color("#ccce35"),
	"ECL":                             lipgloss.Color("#8a1267"),
	"ECLiPSe":                         lipgloss.Color("#001d9d"),
	"EJS":                             lipgloss.Color("#a91e50"),
	"EQ":                              lipgloss.Color("#a78649"),
	"Earthly":                         lipgloss.Color("#2af0ff"),
	"Easybuild":                       lipgloss.Color("#069406"),
	"Ecere Projects":                  lipgloss.Color("#913960"),
	"Ecmarkup":                        lipgloss.Color("#eb8131"),
	"Edge":                            lipgloss.Color("#0dffe0"),
	"EdgeQL":                          lipgloss.Color("#31A7FF"),
	"EditorConfig":                    lipgloss.Color("#fff1f2"),
	"Eiffel":                          lipgloss.Color("#4d6977"),
	"Elixir":                          lipgloss.Color("#6e4a7e"),
	"Elm":                             lipgloss.Color("#60B5CC"),
	"Elvish":                          lipgloss.Color("#55BB55"),
	"Elvish Transcript":               lipgloss.Color("#55BB55"),
	"Emacs Lisp":                      lipgloss.Color("#c065db"),
	"EmberScript":                     lipgloss.Color("#FFF4F3"),
	"Erlang":                          lipgloss.Color("#B83998"),
	"Euphoria":                        lipgloss.Color("#FF790B"),
	"F#":                              lipgloss.Color("#b845fc"),
	"F*":                              lipgloss.Color("#572e30"),
	"FIGlet Font":                     lipgloss.Color("#FFDDBB"),
	"FIRRTL":                          lipgloss.Color("#2f632f"),
	"FLUX":                            lipgloss.Color("#88ccff"),
	"Factor":                          lipgloss.Color("#636746"),
	"Fancy":                           lipgloss.Color("#7b9db4"),
	"Fantom":                          lipgloss.Color("#14253c"),
	"Faust":                           lipgloss.Color("#c37240"),
	"Fennel":                          lipgloss.Color("#fff3d7"),
	"Filebench WML":                   lipgloss.Color("#F6B900"),
	"FlatBuffers":                     lipgloss.Color("#ed284a"),
	"Flix":                            lipgloss.Color("#d44a45"),
	"Fluent":                          lipgloss.Color("#ffcc33"),
	"Forth":                           lipgloss.Color("#341708"),
	"Fortran":                         lipgloss.Color("#4d41b1"),
	"Fortran Free Form":               lipgloss.Color("#4d41b1"),
	"FreeBASIC":                       lipgloss.Color("#141AC9"),
	"FreeMarker":                      lipgloss.Color("#0050b2"),
	"Frege":                           lipgloss.Color("#00cafe"),
	"Futhark":                         lipgloss.Color("#5f021f"),
	"G-code":                          lipgloss.Color("#D08CF2"),
	"GAML":                            lipgloss.Color("#FFC766"),
	"GAMS":                            lipgloss.Color("#f49a22"),
	"GAP":                             lipgloss.Color("#0000cc"),
	"GCC Machine Description":         lipgloss.Color("#FFCFAB"),
	"GDScript":                        lipgloss.Color("#355570"),
	"GDShader":                        lipgloss.Color("#478CBF"),
	"GEDCOM":                          lipgloss.Color("#003058"),
	"GLSL":                            lipgloss.Color("#5686a5"),
	"GSC":                             lipgloss.Color("#FF6800"),
	"Game Maker Language":             lipgloss.Color("#71b417"),
	"Gemfile.lock":                    lipgloss.Color("#701516"),
	"Gemini":                          lipgloss.Color("#ff6900"),
	"Genero 4gl":                      lipgloss.Color("#63408e"),
	"Genero per":                      lipgloss.Color("#d8df39"),
	"Genie":                           lipgloss.Color("#fb855d"),
	"Genshi":                          lipgloss.Color("#951531"),
	"Gentoo Ebuild":                   lipgloss.Color("#9400ff"),
	"Gentoo Eclass":                   lipgloss.Color("#9400ff"),
	"Gerber Image":                    lipgloss.Color("#d20b00"),
	"Gherkin":                         lipgloss.Color("#5B2063"),
	"Git Attributes":                  lipgloss.Color("#F44D27"),
	"Git Commit":                      lipgloss.Color("#F44D27"),
	"Git Config":                      lipgloss.Color("#F44D27"),
	"Git Revision List":               lipgloss.Color("#F44D27"),
	"Gleam":                           lipgloss.Color("#ffaff3"),
	"Glimmer JS":                      lipgloss.Color("#F5835F"),
	"Glimmer TS":                      lipgloss.Color("#3178c6"),
	"Glyph":                           lipgloss.Color("#c1ac7f"),
	"Gnuplot":                         lipgloss.Color("#f0a9f0"),
	"Go":                              lipgloss.Color("#00ADD8"),
	"Go Checksums":                    lipgloss.Color("#00ADD8"),
	"Go Module":                       lipgloss.Color("#00ADD8"),
	"Go Template":                     lipgloss.Color("#00ADD8"),
	"Go Workspace":                    lipgloss.Color("#00ADD8"),
	"Godot Resource":                  lipgloss.Color("#355570"),
	"Golo":                            lipgloss.Color("#88562A"),
	"Gosu":                            lipgloss.Color("#82937f"),
	"Grace":                           lipgloss.Color("#615f8b"),
	"Gradle":                          lipgloss.Color("#02303a"),
	"Gradle Kotlin DSL":               lipgloss.Color("#02303a"),
	"Grammatical Framework":           lipgloss.Color("#ff0000"),
	"GraphQL":                         lipgloss.Color("#e10098"),
	"Graphviz (DOT)":                  lipgloss.Color("#2596be"),
	"Groovy":                          lipgloss.Color("#4298b8"),
	"Groovy Server Pages":             lipgloss.Color("#4298b8"),
	"GtkRC":                           lipgloss.Color("#7fe719"),
	"HAProxy":                         lipgloss.Color("#106da9"),
	"HCL":                             lipgloss.Color("#844FBA"),
	"HIP":                             lipgloss.Color("#4F3A4F"),
	"HLSL":                            lipgloss.Color("#aace60"),
	"HOCON":                           lipgloss.Color("#9ff8ee"),
	"HTML":                            lipgloss.Color("#e34c26"),
	"HTML+ECR":                        lipgloss.Color("#2e1052"),
	"HTML+EEX":                        lipgloss.Color("#6e4a7e"),
	"HTML+ERB":                        lipgloss.Color("#701516"),
	"HTML+PHP":                        lipgloss.Color("#4f5d95"),
	"HTML+Razor":                      lipgloss.Color("#512be4"),
	"HTTP":                            lipgloss.Color("#005C9C"),
	"HXML":                            lipgloss.Color("#f68712"),
	"Hack":                            lipgloss.Color("#878787"),
	"Haml":                            lipgloss.Color("#ece2a9"),
	"Handlebars":                      lipgloss.Color("#f7931e"),
	"Harbour":                         lipgloss.Color("#0e60e3"),
	"Hare":                            lipgloss.Color("#9d7424"),
	"Haskell":                         lipgloss.Color("#5e5086"),
	"Haxe":                            lipgloss.Color("#df7900"),
	"HiveQL":                          lipgloss.Color("#dce200"),
	"HolyC":                           lipgloss.Color("#ffefaf"),
	"Hosts File":                      lipgloss.Color("#308888"),
	"Hurl":                            lipgloss.Color("#FF0288"),
	"Hy":                              lipgloss.Color("#7790B2"),
	"IDL":                             lipgloss.Color("#a3522f"),
	"IGOR Pro":                        lipgloss.Color("#0000cc"),
	"IL Assembly":                     lipgloss.Color("#512BD4"),
	"INI":                             lipgloss.Color("#d1dbe0"),
	"ISPC":                            lipgloss.Color("#2D68B1"),
	"Idris":                           lipgloss.Color("#b30000"),
	"Ignore List":                     lipgloss.Color("#000000"),
	"ImageJ Macro":                    lipgloss.Color("#99AAFF"),
	"Imba":                            lipgloss.Color("#16cec6"),
	"Inno Setup":                      lipgloss.Color("#264b99"),
	"Io":                              lipgloss.Color("#a9188d"),
	"Ioke":                            lipgloss.Color("#078193"),
	"Isabelle":                        lipgloss.Color("#FEFE00"),
	"Isabelle ROOT":                   lipgloss.Color("#FEFE00"),
	"J":                               lipgloss.Color("#9EEDFF"),
	"JAR Manifest":                    lipgloss.Color("#b07219"),
	"JCL":                             lipgloss.Color("#d90e09"),
	"JFlex":                           lipgloss.Color("#DBCA00"),
	"JSON":                            lipgloss.Color("#292929"),
	"JSON with Comments":              lipgloss.Color("#292929"),
	"JSON5":                           lipgloss.Color("#267CB9"),
	"JSONLD":                          lipgloss.Color("#0c479c"),
	"JSONiq":                          lipgloss.Color("#40d47e"),
	"Jac":                             lipgloss.Color("#FC792D"),
	"Jai":                             lipgloss.Color("#ab8b4b"),
	"Janet":                           lipgloss.Color("#0886a5"),
	"Jasmin":                          lipgloss.Color("#d03600"),
	"Java":                            lipgloss.Color("#b07219"),
	"Java Properties":                 lipgloss.Color("#2A6277"),
	"Java Server Pages":               lipgloss.Color("#2A6277"),
	"Java Template Engine":            lipgloss.Color("#2A6277"),
	"JavaScript":                      lipgloss.Color("#f1e05a"),
	"JavaScript+ERB":                  lipgloss.Color("#f1e05a"),
	"Jest Snapshot":                   lipgloss.Color("#15c213"),
	"JetBrains MPS":                   lipgloss.Color("#21D789"),
	"Jinja":                           lipgloss.Color("#a52a22"),
	"Jison":                           lipgloss.Color("#56b3cb"),
	"Jison Lex":                       lipgloss.Color("#56b3cb"),
	"Jolie":                           lipgloss.Color("#843179"),
	"Jsonnet":                         lipgloss.Color("#0064bd"),
	"Julia":                           lipgloss.Color("#a270ba"),
	"Julia REPL":                      lipgloss.Color("#a270ba"),
	"Jupyter Notebook":                lipgloss.Color("#DA5B0B"),
	"Just":                            lipgloss.Color("#384d54"),
	"KCL":                             lipgloss.Color("#7ABABF"),
	"KDL":                             lipgloss.Color("#ffb3b3"),
	"KFramework":                      lipgloss.Color("#4195c5"),
	"KRL":                             lipgloss.Color("#28430A"),
	"Kaitai Struct":                   lipgloss.Color("#773b37"),
	"KakouneScript":                   lipgloss.Color("#6f8042"),
	"KerboScript":                     lipgloss.Color("#41adf0"),
	"KiCad Layout":                    lipgloss.Color("#2f4aab"),
	"KiCad Legacy Layout":             lipgloss.Color("#2f4aab"),
	"KiCad Schematic":                 lipgloss.Color("#2f4aab"),
	"KoLmafia ASH":                    lipgloss.Color("#B9D9B9"),
	"Koka":                            lipgloss.Color("#215166"),
	"Kotlin":                          lipgloss.Color("#A97BFF"),
	"LFE":                             lipgloss.Color("#4C3023"),
	"LLVM":                            lipgloss.Color("#185619"),
	"LOLCODE":                         lipgloss.Color("#cc9900"),
	"LSL":                             lipgloss.Color("#3d9970"),
	"LabVIEW":                         lipgloss.Color("#fede06"),
	"Lambdapi":                        lipgloss.Color("#8027a3"),
	"Langium":                         lipgloss.Color("#2c8c87"),
	"Lark":                            lipgloss.Color("#2980B9"),
	"Lasso":                           lipgloss.Color("#999999"),
	"Latte":                           lipgloss.Color("#f2a542"),
	"Leo":                             lipgloss.Color("#C4FFC2"),
	"Less":                            lipgloss.Color("#1d365d"),
	"Lex":                             lipgloss.Color("#DBCA00"),
	"LigoLANG":                        lipgloss.Color("#0e74ff"),
	"LilyPond":                        lipgloss.Color("#9ccc7c"),
	"Liquid":                          lipgloss.Color("#67b8de"),
	"Liquidsoap":                      lipgloss.Color("#990066"),
	"Literate Agda":                   lipgloss.Color("#315665"),
	"Literate CoffeeScript":           lipgloss.Color("#244776"),
	"Literate Haskell":                lipgloss.Color("#5e5086"),
	"LiveCode Script":                 lipgloss.Color("#0c5ba5"),
	"LiveScript":                      lipgloss.Color("#499886"),
	"Logtalk":                         lipgloss.Color("#295b9a"),
	"LookML":                          lipgloss.Color("#652B81"),
	"Lua":                             lipgloss.Color("#000080"),
	"Luau":                            lipgloss.Color("#00A2FF"),
	"M3U":                             lipgloss.Color("#179C7D"),
	"MATLAB":                          lipgloss.Color("#e16737"),
	"MAXScript":                       lipgloss.Color("#00a6a6"),
	"MDX":                             lipgloss.Color("#fcb32c"),
	"MLIR":                            lipgloss.Color("#5EC8DB"),
	"MQL4":                            lipgloss.Color("#62A8D6"),
	"MQL5":                            lipgloss.Color("#4A76B8"),
	"MTML":                            lipgloss.Color("#b7e1f4"),
	"Macaulay2":                       lipgloss.Color("#d8ffff"),
	"Makefile":                        lipgloss.Color("#427819"),
	"Mako":                            lipgloss.Color("#7e858d"),
	"Markdown":                        lipgloss.Color("#083fa1"),
	"Marko":                           lipgloss.Color("#42bff2"),
	"Mask":                            lipgloss.Color("#f97732"),
	"Mathematical Programming System": lipgloss.Color("#0530ad"),
	"Max":                             lipgloss.Color("#c4a79c"),
	"MeTTa":                           lipgloss.Color("#6a5acd"),
	"Mercury":                         lipgloss.Color("#ff2b2b"),
	"Mermaid":                         lipgloss.Color("#ff3670"),
	"Meson":                           lipgloss.Color("#007800"),
	"Metal":                           lipgloss.Color("#8f14e9"),
	"MiniYAML":                        lipgloss.Color("#ff1111"),
	"MiniZinc":                        lipgloss.Color("#06a9e6"),
	"Mint":                            lipgloss.Color("#02b046"),
	"Mirah":                           lipgloss.Color("#c7a938"),
	"Modelica":                        lipgloss.Color("#de1d31"),
	"Modula-2":                        lipgloss.Color("#10253f"),
	"Modula-3":                        lipgloss.Color("#223388"),
	"Mojo":                            lipgloss.Color("#ff4c1f"),
	"Monkey C":                        lipgloss.Color("#8D6747"),
	"MoonBit":                         lipgloss.Color("#b92381"),
	"MoonScript":                      lipgloss.Color("#ff4585"),
	"Motoko":                          lipgloss.Color("#fbb03b"),
	"Motorola 68K Assembly":           lipgloss.Color("#005daa"),
	"Move":                            lipgloss.Color("#4a137a"),
	"Mustache":                        lipgloss.Color("#724b3b"),
	"NCL":                             lipgloss.Color("#28431f"),
	"NMODL":                           lipgloss.Color("#00356B"),
	"NPM Config":                      lipgloss.Color("#cb3837"),
	"NWScript":                        lipgloss.Color("#111522"),
	"Nasal":                           lipgloss.Color("#1d2c4e"),
	"Nearley":                         lipgloss.Color("#990000"),
	"Nemerle":                         lipgloss.Color("#3d3c6e"),
	"NetLinx":                         lipgloss.Color("#0aa0ff"),
	"NetLinx+ERB":                     lipgloss.Color("#747faa"),
	"NetLogo":                         lipgloss.Color("#ff6375"),
	"NewLisp":                         lipgloss.Color("#87AED7"),
	"Nextflow":                        lipgloss.Color("#3ac486"),
	"Nginx":                           lipgloss.Color("#009639"),
	"Nickel":                          lipgloss.Color("#E0C3FC"),
	"Nim":                             lipgloss.Color("#ffc200"),
	"Nit":                             lipgloss.Color("#009917"),
	"Nix":                             lipgloss.Color("#7e7eff"),
	"Noir":                            lipgloss.Color("#2f1f49"),
	"Nu":                              lipgloss.Color("#c9df40"),
	"NumPy":                           lipgloss.Color("#9C8AF9"),
	"Nunjucks":                        lipgloss.Color("#3d8137"),
	"Nushell":                         lipgloss.Color("#4E9906"),
	"OASv2-json":                      lipgloss.Color("#85ea2d"),
	"OASv2-yaml":                      lipgloss.Color("#85ea2d"),
	"OASv3-json":                      lipgloss.Color("#85ea2d"),
	"OASv3-yaml":                      lipgloss.Color("#85ea2d"),
	"OCaml":                           lipgloss.Color("#ef7a08"),
	"OMNeT++ MSG":                     lipgloss.Color("#a0e0a0"),
	"OMNeT++ NED":                     lipgloss.Color("#08607c"),
	"ObjectScript":                    lipgloss.Color("#424893"),
	"Objective-C":                     lipgloss.Color("#438eff"),
	"Objective-C++":                   lipgloss.Color("#6866fb"),
	"Objective-J":                     lipgloss.Color("#ff0c5a"),
	"Odin":                            lipgloss.Color("#60AFFE"),
	"Omgrofl":                         lipgloss.Color("#cabbff"),
	"Opal":                            lipgloss.Color("#f7ede0"),
	"Open Policy Agent":               lipgloss.Color("#7d9199"),
	"OpenAPI Specification v2":        lipgloss.Color("#85ea2d"),
	"OpenAPI Specification v3":        lipgloss.Color("#85ea2d"),
	"OpenCL":                          lipgloss.Color("#ed2e2d"),
	"OpenEdge ABL":                    lipgloss.Color("#5ce600"),
	"OpenQASM":                        lipgloss.Color("#AA70FF"),
	"OpenSCAD":                        lipgloss.Color("#e5cd45"),
	"Option List":                     lipgloss.Color("#476732"),
	"Org":                             lipgloss.Color("#77aa99"),
	"OverPy":                          lipgloss.Color("#78b355"),
	"OverpassQL":                      lipgloss.Color("#cce2aa"),
	"Oxygene":                         lipgloss.Color("#cdd0e3"),
	"Oz":                              lipgloss.Color("#fab738"),
	"P4":                              lipgloss.Color("#7055b5"),
	"PDDL":                            lipgloss.Color("#0d00ff"),
	"PEG.js":                          lipgloss.Color("#234d6b"),
	"PHP":                             lipgloss.Color("#4F5D95"),
	"PLSQL":                           lipgloss.Color("#dad8d8"),
	"PLpgSQL":                         lipgloss.Color("#336790"),
	"POV-Ray SDL":                     lipgloss.Color("#6bac65"),
	"Pact":                            lipgloss.Color("#F7A8B8"),
	"Pan":                             lipgloss.Color("#cc0000"),
	"Papyrus":                         lipgloss.Color("#6600cc"),
	"Parrot":                          lipgloss.Color("#f3ca0a"),
	"Pascal":                          lipgloss.Color("#E3F171"),
	"Pawn":                            lipgloss.Color("#dbb284"),
	"Pep8":                            lipgloss.Color("#C76F5B"),
	"Perl":                            lipgloss.Color("#0298c3"),
	"PicoLisp":                        lipgloss.Color("#6067af"),
	"PigLatin":                        lipgloss.Color("#fcd7de"),
	"Pike":                            lipgloss.Color("#005390"),
	"Pip Requirements":                lipgloss.Color("#FFD343"),
	"Pkl":                             lipgloss.Color("#6b9543"),
	"PlantUML":                        lipgloss.Color("#fbbd16"),
	"PogoScript":                      lipgloss.Color("#d80074"),
	"Polar":                           lipgloss.Color("#ae81ff"),
	"Portugol":                        lipgloss.Color("#f8bd00"),
	"PostCSS":                         lipgloss.Color("#dc3a0c"),
	"PostScript":                      lipgloss.Color("#da291c"),
	"Power Query":                     lipgloss.Color("#d38e0d"),
	"PowerBuilder":                    lipgloss.Color("#8f0f8d"),
	"PowerShell":                      lipgloss.Color("#012456"),
	"Praat":                           lipgloss.Color("#c8506d"),
	"Prisma":                          lipgloss.Color("#0c344b"),
	"Pro*C":                           lipgloss.Color("#bb8368"),
	"Processing":                      lipgloss.Color("#0096D8"),
	"Procfile":                        lipgloss.Color("#3B2F63"),
	"Prolog":                          lipgloss.Color("#74283c"),
	"Promela":                         lipgloss.Color("#de0000"),
	"Propeller Spin":                  lipgloss.Color("#7fa2a7"),
	"Pug":                             lipgloss.Color("#a86454"),
	"Puppet":                          lipgloss.Color("#302B6D"),
	"PureBasic":                       lipgloss.Color("#5a6986"),
	"PureScript":                      lipgloss.Color("#1D222D"),
	"Pyret":                           lipgloss.Color("#ee1e10"),
	"Python":                          lipgloss.Color("#3572A5"),
	"Python console":                  lipgloss.Color("#3572A5"),
	"Python traceback":                lipgloss.Color("#3572A5"),
	"Q#":                              lipgloss.Color("#fed659"),
	"QML":                             lipgloss.Color("#44a51c"),
	"Qt Script":                       lipgloss.Color("#00b841"),
	"Quake":                           lipgloss.Color("#882233"),
	"QuakeC":                          lipgloss.Color("#975777"),
	"QuickBASIC":                      lipgloss.Color("#008080"),
	"Quint":                           lipgloss.Color("#9d6ce5"),
	"R":                               lipgloss.Color("#198CE7"),
	"RAML":                            lipgloss.Color("#77d9fb"),
	"RAScript":                        lipgloss.Color("#2C97FA"),
	"RBS":                             lipgloss.Color("#701516"),
	"RDoc":                            lipgloss.Color("#701516"),
	"REXX":                            lipgloss.Color("#d90e09"),
	"RMarkdown":                       lipgloss.Color("#198ce7"),
	"RON":                             lipgloss.Color("#a62c00"),
	"ROS Interface":                   lipgloss.Color("#22314e"),
	"RPGLE":                           lipgloss.Color("#2BDE21"),
	"RUNOFF":                          lipgloss.Color("#665a4e"),
	"Racket":                          lipgloss.Color("#3c5caa"),
	"Ragel":                           lipgloss.Color("#9d5200"),
	"Raku":                            lipgloss.Color("#0000fb"),
	"Rascal":                          lipgloss.Color("#fffaa0"),
	"ReScript":                        lipgloss.Color("#ed5051"),
	"Reason":                          lipgloss.Color("#ff5847"),
	"ReasonLIGO":                      lipgloss.Color("#ff5847"),
	"Rebol":                           lipgloss.Color("#358a5b"),
	"Record Jar":                      lipgloss.Color("#0673ba"),
	"Red":                             lipgloss.Color("#f50000"),
	"Redscript":                       lipgloss.Color("#f44336"),
	"Regular Expression":              lipgloss.Color("#009a00"),
	"Ren'Py":                          lipgloss.Color("#ff7f7f"),
	"Rez":                             lipgloss.Color("#FFDAB3"),
	"Ring":                            lipgloss.Color("#2D54CB"),
	"Riot":                            lipgloss.Color("#A71E49"),
	"RobotFramework":                  lipgloss.Color("#00c0b5"),
	"Roc":                             lipgloss.Color("#7c38f5"),
	"Rocq Prover":                     lipgloss.Color("#d0b68c"),
	"Roff":                            lipgloss.Color("#ecdebe"),
	"Roff Manpage":                    lipgloss.Color("#ecdebe"),
	"Rouge":                           lipgloss.Color("#cc0088"),
	"RouterOS Script":                 lipgloss.Color("#DE3941"),
	"Ruby":                            lipgloss.Color("#701516"),
	"Rust":                            lipgloss.Color("#dea584"),
	"SAS":                             lipgloss.Color("#B34936"),
	"SCSS":                            lipgloss.Color("#c6538c"),
	"SPARQL":                          lipgloss.Color("#0C4597"),
	"SQF":                             lipgloss.Color("#3F3F3F"),
	"SQL":                             lipgloss.Color("#e38c00"),
	"SQLPL":                           lipgloss.Color("#e38c00"),
	"SRecode Template":                lipgloss.Color("#348a34"),
	"STL":                             lipgloss.Color("#373b5e"),
	"SVG":                             lipgloss.Color("#ff9900"),
	"Sail":                            lipgloss.Color("#259dd5"),
	"SaltStack":                       lipgloss.Color("#646464"),
	"Sass":                            lipgloss.Color("#a53b70"),
	"Scala":                           lipgloss.Color("#c22d40"),
	"Scaml":                           lipgloss.Color("#bd181a"),
	"Scenic":                          lipgloss.Color("#fdc700"),
	"Scheme":                          lipgloss.Color("#1e4aec"),
	"Scilab":                          lipgloss.Color("#ca0f21"),
	"Self":                            lipgloss.Color("#0579aa"),
	"ShaderLab":                       lipgloss.Color("#222c37"),
	"Shell":                           lipgloss.Color("#89e051"),
	"ShellCheck Config":               lipgloss.Color("#cecfcb"),
	"Shen":                            lipgloss.Color("#120F14"),
	"Simple File Verification":        lipgloss.Color("#C9BFED"),
	"Singularity":                     lipgloss.Color("#64E6AD"),
	"Slang":                           lipgloss.Color("#1fbec9"),
	"Slash":                           lipgloss.Color("#007eff"),
	"Slice":                           lipgloss.Color("#003fa2"),
	"Slim":                            lipgloss.Color("#2b2b2b"),
	"Slint":                           lipgloss.Color("#2379F4"),
	"SmPL":                            lipgloss.Color("#c94949"),
	"Smalltalk":                       lipgloss.Color("#596706"),
	"Smarty":                          lipgloss.Color("#f0c040"),
	"Smithy":                          lipgloss.Color("#c44536"),
	"Snakemake":                       lipgloss.Color("#419179"),
	"Solidity":                        lipgloss.Color("#AA6746"),
	"SourcePawn":                      lipgloss.Color("#f69e1d"),
	"SpiceDB Schema":                  lipgloss.Color("#a5318a"),
	"Squirrel":                        lipgloss.Color("#800000"),
	"Stan":                            lipgloss.Color("#b2011d"),
	"Standard ML":                     lipgloss.Color("#dc566d"),
	"Starlark":                        lipgloss.Color("#76d275"),
	"Stata":                           lipgloss.Color("#1a5f91"),
	"StringTemplate":                  lipgloss.Color("#3fb34f"),
	"Stylus":                          lipgloss.Color("#ff6347"),
	"SubRip Text":                     lipgloss.Color("#9e0101"),
	"SugarSS":                         lipgloss.Color("#2fcc9f"),
	"SuperCollider":                   lipgloss.Color("#46390b"),
	"SurrealQL":                       lipgloss.Color("#ff00a0"),
	"Survex data":                     lipgloss.Color("#ffcc99"),
	"Svelte":                          lipgloss.Color("#ff3e00"),
	"Sway":                            lipgloss.Color("#00F58C"),
	"Sweave":                          lipgloss.Color("#198ce7"),
	"Swift":                           lipgloss.Color("#F05138"),
	"SystemVerilog":                   lipgloss.Color("#DAE1C2"),
	"TI Program":                      lipgloss.Color("#A0AA87"),
	"TL-Verilog":                      lipgloss.Color("#C40023"),
	"TLA":                             lipgloss.Color("#4b0079"),
	"TMDL":                            lipgloss.Color("#f0c913"),
	"TOML":                            lipgloss.Color("#9c4221"),
	"TSQL":                            lipgloss.Color("#e38c00"),
	"TSV":                             lipgloss.Color("#237346"),
	"TSX":                             lipgloss.Color("#3178c6"),
	"TXL":                             lipgloss.Color("#0178b8"),
	"Tact":                            lipgloss.Color("#48b5ff"),
	"Talon":                           lipgloss.Color("#333333"),
	"Tcl":                             lipgloss.Color("#e4cc98"),
	"TeX":                             lipgloss.Color("#3D6117"),
	"Teal":                            lipgloss.Color("#00B1BC"),
	"Terra":                           lipgloss.Color("#00004c"),
	"Terraform Template":              lipgloss.Color("#7b42bb"),
	"TextGrid":                        lipgloss.Color("#c8506d"),
	"TextMate Properties":             lipgloss.Color("#df66e4"),
	"Textile":                         lipgloss.Color("#ffe7ac"),
	"Thrift":                          lipgloss.Color("#D12127"),
	"Toit":                            lipgloss.Color("#c2c9fb"),
	"Tor Config":                      lipgloss.Color("#59316b"),
	"Tree-sitter Query":               lipgloss.Color("#8ea64c"),
	"Turing":                          lipgloss.Color("#cf142b"),
	"Twig":                            lipgloss.Color("#c1d026"),
	"TypeScript":                      lipgloss.Color("#3178c6"),
	"TypeSpec":                        lipgloss.Color("#4A3665"),
	"Typst":                           lipgloss.Color("#239dad"),
	"Unified Parallel C":              lipgloss.Color("#4e3617"),
	"Unity3D Asset":                   lipgloss.Color("#222c37"),
	"Uno":                             lipgloss.Color("#9933cc"),
	"UnrealScript":                    lipgloss.Color("#a54c4d"),
	"Untyped Plutus Core":             lipgloss.Color("#36adbd"),
	"UrWeb":                           lipgloss.Color("#ccccee"),
	"V":                               lipgloss.Color("#4f87c4"),
	"VBA":                             lipgloss.Color("#867db1"),
	"VBScript":                        lipgloss.Color("#15dcdc"),
	"VCL":                             lipgloss.Color("#148AA8"),
	"VHDL":                            lipgloss.Color("#adb2cb"),
	"Vala":                            lipgloss.Color("#a56de2"),
	"Valve Data Format":               lipgloss.Color("#f26025"),
	"Velocity Template Language":      lipgloss.Color("#507cff"),
	"Vento":                           lipgloss.Color("#ff0080"),
	"Verilog":                         lipgloss.Color("#b2b7f8"),
	"Vim Help File":                   lipgloss.Color("#199f4b"),
	"Vim Script":                      lipgloss.Color("#199f4b"),
	"Vim Snippet":                     lipgloss.Color("#199f4b"),
	"Visual Basic .NET":               lipgloss.Color("#945db7"),
	"Visual Basic 6.0":                lipgloss.Color("#2c6353"),
	"Volt":                            lipgloss.Color("#1F1F1F"),
	"Vue":                             lipgloss.Color("#41b883"),
	"Vyper":                           lipgloss.Color("#9F4CF2"),
	"WDL":                             lipgloss.Color("#42f1f4"),
	"WGSL":                            lipgloss.Color("#1a5e9a"),
	"Web Ontology Language":           lipgloss.Color("#5b70bd"),
	"WebAssembly":                     lipgloss.Color("#04133b"),
	"WebAssembly Interface Type":      lipgloss.Color("#6250e7"),
	"Whiley":                          lipgloss.Color("#d5c397"),
	"Wikitext":                        lipgloss.Color("#fc5757"),
	"Windows Registry Entries":        lipgloss.Color("#52d5ff"),
	"Witcher Script":                  lipgloss.Color("#ff0000"),
	"Wolfram Language":                lipgloss.Color("#dd1100"),
	"Wollok":                          lipgloss.Color("#a23738"),
	"World of Warcraft Addon Data":    lipgloss.Color("#f7e43f"),
	"Wren":                            lipgloss.Color("#383838"),
	"X10":                             lipgloss.Color("#4B6BEF"),
	"XC":                              lipgloss.Color("#99DA07"),
	"XML":                             lipgloss.Color("#0060ac"),
	"XML Property List":               lipgloss.Color("#0060ac"),
	"XQuery":                          lipgloss.Color("#5232e7"),
	"XSLT":                            lipgloss.Color("#EB8CEB"),
	"Xmake":                           lipgloss.Color("#22a079"),
	"Xojo":                            lipgloss.Color("#81bd41"),
	"Xonsh":                           lipgloss.Color("#285EEF"),
	"Xtend":                           lipgloss.Color("#24255d"),
	"YAML":                            lipgloss.Color("#cb171e"),
	"YARA":                            lipgloss.Color("#220000"),
	"YASnippet":                       lipgloss.Color("#32AB90"),
	"Yacc":                            lipgloss.Color("#4B6C4B"),
	"Yul":                             lipgloss.Color("#794932"),
	"ZAP":                             lipgloss.Color("#0d665e"),
	"ZIL":                             lipgloss.Color("#dc75e5"),
	"ZenScript":                       lipgloss.Color("#00BCD1"),
	"Zephir":                          lipgloss.Color("#118f9e"),
	"Zig":                             lipgloss.Color("#ec915c"),
	"Zimpl":                           lipgloss.Color("#d67711"),
	"Zmodel":                          lipgloss.Color("#ff7100"),
	"crontab":                         lipgloss.Color("#ead7ac"),
	"eC":                              lipgloss.Color("#913960"),
	"fish":                            lipgloss.Color("#4aae47"),
	"hoon":                            lipgloss.Color("#00b171"),
	"iCalendar":                       lipgloss.Color("#ec564c"),
	"jq":                              lipgloss.Color("#c7254e"),
	"kvlang":                          lipgloss.Color("#1da6e0"),
	"mIRC Script":                     lipgloss.Color("#3d57c3"),
	"mcfunction":                      lipgloss.Color("#E22837"),
	"mdsvex":                          lipgloss.Color("#5f9ea0"),
	"mupad":                           lipgloss.Color("#244963"),
	"nanorc":                          lipgloss.Color("#2d004d"),
	"nesC":                            lipgloss.Color("#94B0C7"),
	"ooc":                             lipgloss.Color("#b0b77e"),
	"pkg-config":                      lipgloss.Color("#2b5e82"),
	"q":                               lipgloss.Color("#0040cd"),
	"reStructuredText":                lipgloss.Color("#141414"),
	"sed":                             lipgloss.Color("#64b970"),
	"templ":                           lipgloss.Color("#66D0DD"),
	"vCard":                           lipgloss.Color("#ee2647"),
	"wisp":                            lipgloss.Color("#7582D1"),
	"xBase":                           lipgloss.Color("#403a40"),
}
